### ISSUE TITLE
Stringtable.xml

### ISSUE THREAD

**Issue by jus61** [Defent/DMS_Exile#25]
Could you please install a Stringtable.xml

**Comment by eraser1** [comment]
No, and here are my reasons:

1) You would need the stringtable to exist on the client, otherwise it would localize text based on server locality, which defeats the purpose. DMS is currently written to exist only as a simple server-side addon. We will probably make a client-side GUI simple addon eventually to make mission info appear better, but that's a long ways away. There are several, several things to do before that.

2) Neither Defent nor I have the ability, time, or motivation to translate the mission texts into various languages.

3) There's hardly any point to localizing mission text, at least at this stage. Exile is written pretty much entirely in English. All of mod-specific texts are in English. If a player doesn't understand English well enough to understand Exile messages, it's not really gonna help if the occasional AI mission message is localized to the player's language.
