### ISSUE TITLE
Error on log

### ISSUE THREAD

**Issue by M3ragon** [Defent/DMS_Exile#44]
Use Exile 1.0.0 Tanoa
1. 4:08:10 "DMS SORT OF AN ERROR :: Null Group found in DMS_FrozenAIGroups! Index: 6"
1. Error:
   9:30:28 "DMS ERROR :: Number of attempts in DMS_fnc_findSafePos (5000) reached maximum number of attempts!"
   9:30:28 Error in expression <_this;
   };
   };

private _parsedParams =
[
_missionPosition,
_extraParams
];

if (D>
 9:30:28   Error position: <_missionPosition,
_extraParams
];

if (D>
 9:30:28   Error Undefined variable in expression: _missionposition
 9:30:28 File x\addons\dms\scripts\fn_MissionParams.sqf, line 135
 9:30:28 "DMS ERROR :: Called MISSION construction.sqf with invalid parameters: [[25,500,0.9,2500,2500,2500,2000,100,true],[[]],[]]"

rpt:
[arma3server_2016-07-17_00-44-21.txt](https://github.com/Defent/DMS_Exile/files/367725/arma3server_2016-07-17_00-44-21.txt)

**Comment by eraser1** [comment]
The first "issue" happens when an AI group is killed while frozen. This might happen when you don't check for frozen groups often enough. You can eliminate this by reducing the value of the following config: `DMS_ai_freezeCheckingDelay`

Please read [my reply to "Cael817" on the linked post](http://www.exilemod.com/topic/61-dms-defents-mission-system/?do=findComment&comment=111346) for the second part.
