### ISSUE TITLE
Reinforcements have no launchers.

### ISSUE THREAD

**Issue by Ravenger2709** [Defent/DMS_Exile#78]
Hello! Yesterday i seen that reinforcments have no launchers, but launchers chance is 100 and all bots have it then mission starts. What i need to do?
Thx.

**Comment by eraser1** [comment]
Hi.
This occurs because [fn_GroupReinforcementsManager](https://github.com/Defent/DMS_Exile/blob/master/%40ExileServer/addons/a3_dms/scripts/fn_GroupReinforcementsManager.sqf#L582-L604) directly calls [fn_SpawnAISoldier](https://github.com/Defent/DMS_Exile/blob/master/%40ExileServer/addons/a3_dms/scripts/fn_SpawnAISoldier.sqf).

The logic which handles adding launchers to units is in [fn_SpawnAIGroup](https://github.com/Defent/DMS_Exile/blob/master/%40ExileServer/addons/a3_dms/scripts/fn_SpawnAIGroup.sqf#L77-L108).

If desired, you can add additional logic to add launchers to reinforcements within the Reinforcements Manager.
