### ISSUE TITLE
Türen verschlossen

### ISSUE THREAD

**Issue by mo1982** [Defent/DMS_Exile#79]
Hallo ich habe das Problem, dass alle Türen von den Missionen(Container, Häuser, u.s.w verschlossen sind. das Problem ist einfach das kein normaler Spieler die Missionen fertig machen kann, da ja auch KI in den Gebäuden ist. Bin im Server Aufbau und Skripten ein ziemlicher Neuling. kann mir einer sagen wie es möglich ist von allen Static and Bandits Missionen die Türen zu öffnen. 
mfg
[DHZ] Swatty
PS: auf der Map Exile Altis gehen sonst alle Türen auf.

**Comment by eraser1** [comment]
Hello,

I don't speak German, but I used Google Translate and it seems that your issue is that the buildings and containers are "locked".

This can occur when "simulation" is disabled on them.
The default "DMS_fnc_ImportFromM3E" function (and its "_Static" variant automatically disable simulation. I don't recall if they import buildings, which would cause this issue. However, if that is the case, you can comment out or remove the following lines:
https://github.com/Defent/DMS_Exile/blob/c523a82cd16f528e950da8fb13c449ac8ce36b76/%40ExileServer/addons/a3_dms/scripts/fn_ImportFromM3E.sqf#L54
https://github.com/Defent/DMS_Exile/blob/48e530bfb517c6276357013dee83c94d4432431b/%40ExileServer/addons/a3_dms/scripts/fn_ImportFromM3E_Static.sqf#L49

If you're making your own missions and importing your own buildings, I highly recommend using the M3E_3DEN editor instead. Within that editor, you should be able to set buildings with simulation enabled or disabled, and you should ensure that simulation is enabled for any buildings with doors.

There are more advanced/nuanced solutions, but I understand that you're not particularly experienced yet, so I will avoid those for now.

**Comment by mo1982** [comment]
still not working. all mission doors are still closed. no changes were made to the server. i just installed it via nitrado on infiStar and installed a3_dms from github. And as i said since the beginning the doors of the static missions are locked even for the new static missions i added from github.

**Comment by mo1982** [comment]
ok i have now set both files from false to true server started and it worked. All doors open now. Thanks for your help

**Comment by eraser1** [comment]
No problem.

Somebody may want to consider modifying the functions such that buildings are simulated dynamically (using the Exile framework, or vanilla functions, for example); alternatively, if there is an easy way to check if the structure has interactive doors, then do not disable simulation for any structures with interactive doors.
